Repository BluRosie/hg-engine, pull requests merged in 2024-05, with the labels that each got.

#240 Modernise Keen Eye and Illuminate. Add Minds Eye
  src/battle/other_battle_calculators.c
  src/individual/btl_scr_cmd_33_statbuffchange.c
Labels: abilities, modernization

#238 Fix #233 and address #199 (hopefully)
  README.md
  armips/move/battle_eff_seq/115.s
  armips/move/battle_eff_seq/136.s
  armips/move/battle_eff_seq/137.s
  armips/move/battle_eff_seq/164.s
  armips/move/battle_eff_seq/319.s
  armips/move/battle_sub_seq/009.s
  bytereplacement
  include/battle.h
  include/debug.h
  src/battle/ability.c
  src/battle/other_battle_calculators.c
  src/battle/weather.c
  src/individual/BattleFormChangeCheck.c
  src/individual/SwitchInAbilityCheck.c
  src/save.c
Labels: bug, help wanted, rom code, moves, modernization, urgent

#243 Updates to a few mechanics
  armips/data/moves.s
  armips/include/move_effects.s
  bytereplacement
  include/battle.h
  include/constants/move_effects.h
  src/battle/ability.c
  src/battle/battle_pokemon.c
  src/battle/battle_start.c
  src/battle/other_battle_calculators.c
  src/individual/CalcBaseDamage.c
Labels: moves, abilities, modernization

#246 Implement and Fix Abilites and Moves
  armips/data/mondata.s
  armips/include/battle_script_constants.s
  armips/include/battlescriptcmd.s
  armips/move/battle_eff_seq/115.s
  armips/move/battle_eff_seq/136.s
  armips/move/battle_eff_seq/137.s
  armips/move/battle_eff_seq/164.s
  armips/move/battle_eff_seq/300.s
  armips/move/battle_sub_seq/006.s
  armips/move/battle_sub_seq/009.s
  armips/move/battle_sub_seq/104.s
  armips/move/battle_sub_seq/175.s
  armips/move/battle_sub_seq/183.s
  armips/move/battle_sub_seq/184.s
  armips/move/battle_sub_seq/185.s
  armips/move/battle_sub_seq/252.s
  armips/move/battle_sub_seq/365.s
  armips/move/battle_sub_seq/366.s
  armips/move/battle_sub_seq/367.s
  armips/move/battle_sub_seq/368.s
  armips/move/battle_sub_seq/369.s
  armips/move/battle_sub_seq/370.s
  armips/move/battle_sub_seq/371.s
  armips/move/battle_sub_seq/372.s
  armips/move/battle_sub_seq/373.s
  data/text/197.txt
  hooks
  include/battle.h
  include/constants/battle_script_constants.h
  rom.ld
  src/battle/ability.c
  src/battle/battle_pokemon.c
  src/battle/battle_script_commands.c
  src/battle/battle_start.c
  src/battle/other_battle_calculators.c
  src/individual/SwitchInAbilityCheck.c
Labels: bug, moves, abilities, modernization

#253 Address miscellaneous TODOs
  armips/data/evodata.s
  armips/data/pokedex/weight.s
  data/BaseExperienceTable.c
  data/itemdata/itemdata.c
  src/battle/ability.c
  src/battle/battle_script_commands.c
Labels: bug, moves, abilities, items, mon expansion, modernization
