Repository BluRosie/hg-engine, pull requests merged in 2024-12, with the labels that each got.

#361 Typo fix
  armips/asm/tm_palettes.s
Labels: enhancement

#358 Converts Flags.s From Hex to Decimal and Update Scriptmacros.s With More Constants
  armips/include/scriptmacros.s
Labels: enhancement

#359 Fix Flittle evo to Espathra
  armips/data/evodata.s
Labels: bug, mon expansion

#349 Disable items in trainer battle
  hooks
  include/battle.h
  include/battle_controller_player.h
  include/config.h
  include/constants/battle_message_constants.h
  rom.ld
  src/battle/battle_controller_player.c
Labels: enhancement, items
