Repository BluRosie/hg-engine, pull requests merged in 2024-04, with the labels that each got.

#223 Implement Dynamic Speed
  include/battle.h
  rom.ld
  src/battle/ability.c
  src/battle/battle_start.c
  src/battle/other_battle_calculators.c
Labels: modernization

#224 Update GetMonEvolutionInternal.c
  src/individual/GetMonEvolutionInternal.c
Labels: modernization

#225 Fix dynamic speed off by 1 error, implement After You and Quash
  armips/data/moves.s
  armips/include/battlescriptcmd.s
  armips/include/constants.s
  armips/move/battle_eff_seq/305.s
  armips/move/battle_eff_seq/306.s
  armips/move/battle_sub_seq/356.s
  armips/move/battle_sub_seq/357.s
  data/text/197.txt
  include/battle.h
  include/constants/battle_script_constants.h
  src/battle/battle_script_commands.c
  src/battle/other_battle_calculators.c
  src/moves.c
Labels: bug, moves, modernization

#227 Update CriticalRateTable
  src/battle/other_battle_calculators.c
Labels: good first issue, modernization

#218 Implement Field Use of Mirror Herb and Pokémon Nursery Mechanics
  hooks
  include/pokemon.h
  rom.ld
  src/battle/battle_pokemon.c
  src/battle/other_battle_calculators.c
  src/field/enemy_party.c
  src/field/script_commands.c
  src/individual/GetMonEvolutionInternal.c
  src/pokemon.c
Labels: modernization

#230 Implementation of Surge Surfer & Grass Pelt
  src/battle/battle_calc_damage.c
  src/battle/other_battle_calculators.c
Labels: good first issue, abilities, modernization
