Repository BluRosie/hg-engine, pull requests merged in 2024-10, with the labels that each got.

#310 Fix for U-Turn bug
  .gitignore
  Makefile
  src/battle/battle_item.c
  src/individual/CheckDefenderItemEffectOnHit.c
Labels: bug, moves, items, modernization

#323 Adjust caps on vitamins and EV totals
  bytereplacement
Labels: items, modernization

#311 Handle contact modern mecanics
  include/battle.h
  src/battle/ability.c
  src/battle/battle_item.c
  src/battle/battle_script_commands.c
  src/battle/other_battle_calculators.c
  src/individual/CalcBaseDamage.c
  src/individual/CheckDefenderItemEffectOnHit.c
  src/individual/MoveHitDefenderAbilityCheck.c
Labels: abilities, items, modernization

#312 End battle item exposure
  hooks
  rom.ld
  src/battle/battle_script_commands.c
Labels: enhancement, abilities, items

#325 Uncaped vanilla candies
  include/config.h
  src/pokemon.c
Labels: enhancement, items

#336 Convert flags.s from hex to decimal
  armips/include/flags.s
  armips/scr_seq/scr_seq_00003_commonscript.s
Labels: enhancement, text

#322 Sticky Web
  armips/data/moves.s
  asm/include/battle_commands.inc
  asm/include/battle_constants.inc
  asm/include/move_effects.inc
  data/battle_scripts/effects/effect_script_0326_STICKY_WEB.s
  data/battle_scripts/subscripts/subscript_0012_UPDATE_STAT_STAGE.s
  data/battle_scripts/subscripts/subscript_0099_HAZARDS_CHECK.s
  data/battle_scripts/subscripts/subscript_0171_DEFOG.s
  data/text/197.txt
  include/battle.h
  include/constants/move_effects.h
  src/battle/battle_pokemon.c
  src/battle/battle_script_commands.c
  src/battle/battle_start.c
Labels: moves, abilities

#331 Else path for tm/hm reuse/forget
  armips/asm/forget_hm.s
  armips/asm/tm.s
  armips/global.s
Labels: enhancement, build system
