Repository BluRosie/hg-engine, pull requests merged in 2025-03, with the labels that each got.

#370 Very Fast HP Bar
  CONFIG.md
  bytereplacement
  include/config.h
Labels: enhancement, suggestion

#326 Ai can use trick
  hooks
  include/config.h
  src/battle/battle_script_commands.c
Labels: ai

#350 Npc trade
  asm/general_hooks.s
  bytereplacement
  hooks
  include/npc_trade.h
  rom.ld
  scripts/make.py
  src/npc_trade.c
Labels: enhancement

#390 Supplement Form Reversion table
  data/FormReversionMapping.c
  data/PokeFormDataTbl.c
  include/config.h
Labels: mon expansion, modernization

#396 Add the proper effect for Eviolite
  src/individual/CalcBaseDamage.c
Labels: items, modernization
