Repository BluRosie/hg-engine, pull requests merged in 2025-06, with the labels that each got.

#434 RareCandy evolves at LevelCap (if possible) with a Config
  .gitignore
  include/config.h
  src/individual/GetMonEvolutionInternal.c
Labels: enhancement

#426 add no partner double battles
  armips/asm/no_partner_double_battles.s
  armips/global.s
  armips/include/config.s
  armips/include/constants.s
Labels: enhancement

#436 Electromorphosis, Wind Power & Wind Rider
  asm/include/battle_constants.inc
  data/battle_scripts/subscripts/subscript_0411_PLAY_EAT_BERRY_ANIMATION.s
  data/battle_scripts/subscripts/subscript_0448_HANDLE_WIND_RIDER.s
  data/battle_scripts/subscripts/subscript_0449_HANDLE_CHARGE_BOOST.s
  data/text/197.txt
  include/battle.h
  include/constants/battle_script_constants.h
  src/battle/ability.c
  src/battle/other_battle_calculators.c
  src/individual/MoveHitDefenderAbilityCheck.c
Labels: abilities

#454 Protect moves
  armips/data/moves.s
  asm/include/battle_commands.inc
  asm/include/battle_constants.inc
  asm/include/move_effects.inc
  data/battle_scripts/effects/effect_script_0371_PROTECT_USER_SIDE.s
  data/battle_scripts/subscripts/subscript_0402_PROTECTED.s
  data/battle_scripts/subscripts/subscript_0450_SPIKY_SHIELD.s
  data/text/197.txt
  hooks
  include/battle.h
  include/constants/battle_message_constants.h
  include/constants/battle_script_constants.h
  include/constants/move_effects.h
  src/battle/ability.c
  src/battle/battle_script_commands.c
  src/individual/BattleController_BeforeMove.c
Labels: moves, abilities
