Repository BluRosie/hg-engine, pull requests merged in 2025-09, with the labels that each got.

#512 Seed Sower
  src/individual/MoveHitDefenderAbilityCheck.c
Labels: abilities

#529 Trace, Sticky Web, no target crash, Fix Dig into Magnet Rise/Levitate bug
  data/battle_scripts/subscripts/subscript_0099_HAZARDS_CHECK.s
  include/battle.h
  src/individual/BattleController_BeforeMove.c
  src/individual/ServerDoPostMoveEffects.c
  src/individual/SwitchInAbilityCheck.c
Labels: bug, abilities

#532 Implement Aurora Veil & Fix Lure, Safari and Sport Ball Rates
  armips/data/moves.s
  asm/include/battle_commands.inc
  asm/include/battle_constants.inc
  asm/include/move_effects.inc
  data/battle_scripts/effects/effect_script_0377_SET_AURORA_VEIL.s
  data/battle_scripts/subscripts/subscript_0171_DEFOG.s
  data/battle_scripts/subscripts/subscript_0457_AURORA_VEIL.s
  data/text/197.txt
  hooks
  include/battle.h
  include/constants/battle_message_constants.h
  include/constants/battle_script_constants.h
  include/constants/move_effects.h
  src/battle/battle_calc_damage.c
  src/battle/battle_script_commands.c
  src/individual/BattleController_BeforeMove.c
  src/individual/CalculateBallShakes.c
  src/individual/ServerFieldConditionCheck.c
  src/moves.c
Labels: suggestion, moves
