Repository BluRosie/hg-engine, pull requests merged in 2025-08, with the labels that each got.

#481 Fix Yawn status check
  src/individual/BattleController_BeforeMove.c
Labels: bug, moves

#483 fix beat up
  hooks
  include/battle.h
  src/battle/battle_pokemon.c
  src/battle/battle_script_commands.c
  src/individual/CalcBaseDamage.c
Labels: moves, modernization

#480 allow repeated item use
  asm/general_hooks.s
  hooks
  include/party_menu.h
  include/pokemon.h
  include/script.h
  rom.ld
  src/party_menu.c
Labels: enhancement

#494 Fix Incinerate, First Impression
  armips/data/moves.s
  asm/include/move_effects.inc
  data/battle_scripts/effects/effect_script_0373_FIRST_TURN_ONLY.s
  include/constants/move_effects.h
Labels: moves

#500 more mac-compatible battle gfx rm command
  narcs.mk
Labels: bug, build system

#518 Fix catch formula
  src/individual/CalculateBallShakes.c
Labels: bug

#501 Implement config to disallow Dexited and Unimplemented moves
  CONFIG.md
  armips/data/moves.s
  armips/include/config.s
  armips/include/movemacros.s
  data/text/197.txt
  include/battle.h
  include/debug.h
  src/battle/other_battle_calculators.c
Labels: enhancement, moves, modernization

#503 add sand spit to MoveHitDefenderAbilityCheck
  src/battle/battle_script_commands.c
  src/individual/MoveHitDefenderAbilityCheck.c
Labels: abilities
